/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPracticarRouteImport } from './routes/_authenticated/practicar'
import { Route as AuthenticatedTiradaRouteImport } from './routes/_authenticated/tirada'
import { Route as AuthenticatedCartasIndexRouteImport } from './routes/_authenticated/cartas.index'
import { Route as AuthenticatedCartasSlugRouteImport } from './routes/_authenticated/cartas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticarRoute = AuthenticatedPracticarRouteImport.update({
  id: '/practicar',
  path: '/practicar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTiradaRoute = AuthenticatedTiradaRouteImport.update({
  id: '/tirada',
  path: '/tirada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartasIndexRoute =
  AuthenticatedCartasIndexRouteImport.update({
    id: '/cartas/',
    path: '/cartas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartasSlugRoute = AuthenticatedCartasSlugRouteImport.update({
  id: '/cartas/$slug',
  path: '/cartas/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/practicar': typeof AuthenticatedPracticarRoute
  '/tirada': typeof AuthenticatedTiradaRoute
  '/cartas/$slug': typeof AuthenticatedCartasSlugRoute
  '/cartas/': typeof AuthenticatedCartasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/practicar': typeof AuthenticatedPracticarRoute
  '/tirada': typeof AuthenticatedTiradaRoute
  '/cartas/$slug': typeof AuthenticatedCartasSlugRoute
  '/cartas': typeof AuthenticatedCartasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/practicar': typeof AuthenticatedPracticarRoute
  '/_authenticated/tirada': typeof AuthenticatedTiradaRoute
  '/_authenticated/cartas/$slug': typeof AuthenticatedCartasSlugRoute
  '/_authenticated/cartas/': typeof AuthenticatedCartasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/inicio'
    | '/perfil'
    | '/practicar'
    | '/tirada'
    | '/cartas/$slug'
    | '/cartas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/inicio'
    | '/perfil'
    | '/practicar'
    | '/tirada'
    | '/cartas/$slug'
    | '/cartas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/favoritos'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/practicar'
    | '/_authenticated/tirada'
    | '/_authenticated/cartas/$slug'
    | '/_authenticated/cartas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practicar': {
      id: '/_authenticated/practicar'
      path: '/practicar'
      fullPath: '/practicar'
      preLoaderRoute: typeof AuthenticatedPracticarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tirada': {
      id: '/_authenticated/tirada'
      path: '/tirada'
      fullPath: '/tirada'
      preLoaderRoute: typeof AuthenticatedTiradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartas/': {
      id: '/_authenticated/cartas/'
      path: '/cartas'
      fullPath: '/cartas/'
      preLoaderRoute: typeof AuthenticatedCartasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartas/$slug': {
      id: '/_authenticated/cartas/$slug'
      path: '/cartas/$slug'
      fullPath: '/cartas/$slug'
      preLoaderRoute: typeof AuthenticatedCartasSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPracticarRoute: typeof AuthenticatedPracticarRoute
  AuthenticatedTiradaRoute: typeof AuthenticatedTiradaRoute
  AuthenticatedCartasSlugRoute: typeof AuthenticatedCartasSlugRoute
  AuthenticatedCartasIndexRoute: typeof AuthenticatedCartasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPracticarRoute: AuthenticatedPracticarRoute,
  AuthenticatedTiradaRoute: AuthenticatedTiradaRoute,
  AuthenticatedCartasSlugRoute: AuthenticatedCartasSlugRoute,
  AuthenticatedCartasIndexRoute: AuthenticatedCartasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
